package Lojinha.GUI.Vendas;

import Lojinha.Entidades.Caixa;
import Lojinha.Entidades.Cliente;
import Lojinha.Entidades.Produto;
import Lojinha.Entidades.Vendas;
import Lojinha.RN.CaixaRN;
import Lojinha.RN.ClienteRN;
import Lojinha.RN.ProdutoRN;
import Lojinha.RN.VendasRN;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class FormCadastro extends javax.swing.JFrame {

    ClienteRN clienteRN;
    ProdutoRN produtoRN;
    VendasRN vendasRN;
    Produto produto;
    Cliente cliente;

    public FormCadastro() {

        initComponents();
        setLocation(500, 100);
        jLabelCliente.setVisible(false);
        jLabelProduto.setVisible(false);
        jLabelQtd.setVisible(false);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                fechar();
                new FormVendas().setVisible(true);
            }
        });
    }

    public void fechar() {
        this.dispose();
    }

    public void verificarCliente() {
        // cliente
        if (jTextIdCliente.getText().isEmpty()) {
            jLabelCliente.setText("Digite o nome");
        } else {
            clienteRN = new ClienteRN();
            String nome = jTextIdCliente.getText();

            try {
                cliente = clienteRN.buscarNome(nome).get(0);
            } catch (Throwable e) {
                produto = null;
            }
            if (cliente != null) {
                jLabelCliente.setText(cliente.getNome()
                        + " (" + cliente.getDescricao() + ")");
            } else {
                jLabelCliente.setText("Cliente não encontrado");
            }
        }
        jLabelCliente.setVisible(true);
    }

    public void verificarProduto() {
        //produto
        if (jTextIdProduto.getText().isEmpty()) {
            jLabelProduto.setText("Digite o nome");
        } else {
            produtoRN = new ProdutoRN();

            String nome = jTextIdProduto.getText();

            try {
                produto = produtoRN.buscarNome(nome).get(0);
            } catch (Throwable e) {
                produto = null;
            }
            if (produto != null) {
                jLabelProduto.setText(produto.getId()
                        + " : " + produto.getNome());
                jTextPreco.setText("" + produto.getPrecoVenda());
                jLabelQtd.setText("Máx : " + produto.getQuantidade());
            } else {
                jLabelProduto.setText("Produto não encontrado");
            }
        }
        jLabelProduto.setVisible(true);
        jLabelQtd.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jTextIdCliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextIdProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextQtd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextPreco = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabelQtd = new javax.swing.JLabel();
        jLabelProduto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Nova Venda");
        setResizable(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/novo_32x32.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel2.setText("Nova Venda");

        jLabelCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelCliente.setText("Cliente não encontrado");

        jTextIdCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdClienteActionPerformed(evt);
            }
        });
        jTextIdCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextIdClienteKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lapis_32x32.png"))); // NOI18N
        jButton1.setText("Salvar Venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Produto");

        jTextIdProduto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextIdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdProdutoActionPerformed(evt);
            }
        });
        jTextIdProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextIdProdutoKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Quantidade");

        jTextQtd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQtdActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Pago");

        jTextPreco.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrecoActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unidade", "Total" }));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Cliente");

        jLabelQtd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelQtd.setText("Sem estoque");

        jLabelProduto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelProduto.setText("Produto não encontrado");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Preço   R$");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioButton1.setText("Sim");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Não");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelQtd)))
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //verificarCliente();
        //verificarProduto(); bug no preço
        Vendas venda = new Vendas();
        float preco, quantidade;

        try {
            preco = Float.parseFloat(jTextPreco.getText().replaceAll(",", "."));
            quantidade = Float.parseFloat(jTextQtd.getText().replaceAll(",", "."));

            if ((("".equals(jTextIdCliente.getText())
                    || "".equals(jTextIdProduto.getText()))
                    || "".equals(jTextQtd.getText()))
                    || "".equals(jTextPreco.getText())) {
                JOptionPane.showMessageDialog(null, "Preencha os campos vazios.", "Erro ao salvar venda", 2);

            } else if (produto == null) {
                JOptionPane.showMessageDialog(null, "Digite o id de um produto válido.", "Erro ao salvar venda", 2);

            } else if (cliente == null) {
                JOptionPane.showMessageDialog(null, "Digite o id de um cliente válido.", "Erro ao salvar venda", 2);

            } else if (produto.getQuantidade() < quantidade) {
                JOptionPane.showMessageDialog(null, "Não se pode vender mais do que tem.", "Erro ao salvar venda", 2);

            } else if (quantidade < 1) {
                JOptionPane.showMessageDialog(null, "Não se pode vender quantidade fracionada ou negativa.", "Erro ao salvar venda", 2);

            } else if (preco < 0) {
                JOptionPane.showMessageDialog(null, "Não se pode vender por um preco negativo.", "Erro ao salvar venda", 2);

            } else {

                if (jComboBox1.getSelectedItem() == "Total") {
                    preco = preco / quantidade;
                }

                if (jRadioButton1.isSelected()) {
                    venda.setPago(true);
                } else {
                    venda.setPago(false);
                }

                SimpleDateFormat dataF = new SimpleDateFormat("dd/MM/yyyy");
                String data = dataF.format(new Date(System.currentTimeMillis()));

                venda.setStatus(true);
                venda.setCliente(cliente);
                venda.setProduto(produto);
                venda.setDataVenda(data);
                venda.setPrecoVendido(preco);
                venda.setQuantidade((int) quantidade);

                vendasRN = new VendasRN();
                vendasRN.salvar(venda);

                produto.setQuantidade(produto.getQuantidade() - venda.getQuantidade());
                produtoRN = new ProdutoRN();
                produtoRN.atualizar(produto);

                // Caixa
                if (venda.isPago()) {
                    Caixa caixa = new Caixa();
                    caixa.setDescricao("Venda - " + venda.getProduto().getNome() + " (" + venda.getQuantidade() + ")");
                    caixa.setPreco(preco * quantidade);
                    caixa.setStatus(true);
                    caixa.setTipo(true);
                    caixa.setDataCaixa(data);

                    CaixaRN caixaRN = new CaixaRN();
                    caixaRN.salvar(caixa);
                }

                new FormVendas().setVisible(true);
                this.dispose();
            }
        } catch (Throwable e) {
            JOptionPane.showMessageDialog(null,
                    "O preço e a quantidade devem ser numeros\n"
                    + "Ex: 1,99 e 10", "Erro ao salvar venda", 2);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdProdutoActionPerformed

    }//GEN-LAST:event_jTextIdProdutoActionPerformed

    private void jTextQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQtdActionPerformed

    }//GEN-LAST:event_jTextQtdActionPerformed

    private void jTextPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrecoActionPerformed

    }//GEN-LAST:event_jTextPrecoActionPerformed

    private void jTextIdClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextIdClienteKeyReleased
        verificarCliente();
    }//GEN-LAST:event_jTextIdClienteKeyReleased

    private void jTextIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdClienteActionPerformed

    private void jTextIdProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextIdProdutoKeyReleased
        verificarProduto();
    }//GEN-LAST:event_jTextIdProdutoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelProduto;
    private javax.swing.JLabel jLabelQtd;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextIdCliente;
    private javax.swing.JTextField jTextIdProduto;
    private javax.swing.JTextField jTextPreco;
    private javax.swing.JTextField jTextQtd;
    // End of variables declaration//GEN-END:variables
}
